name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test & Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Installer le SDK .NET (version 9.0.x ici)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Étape 3 : Restaurer les dépendances NuGet
      - name: Restore dependencies
        run: dotnet restore

      # Étape 4 : Démarrer l’analyse SonarCloud (dotnet sonarscanner begin)
      # -k (key) : identifiant du projet dans SonarCloud
      # -o (organization) : organisation SonarCloud
      # /d:sonar.login : token d’authentification sécurisé
      - name: SonarCloud Begin
        run: dotnet sonarscanner begin /k:"EduCaninDeploy" /o:"said-develops" /d:sonar.login=${{ secrets.SONAR_TOKEN }}

      # Étape 5 : Compiler le projet (après begin)
      - name: Build
        run: dotnet build --no-restore

      # Étape 6 : Exécuter les tests unitaires
      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Étape 7 : Terminer l’analyse SonarCloud (dotnet sonarscanner end)
      - name: SonarCloud End
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
