name: UnitTest

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and test
    runs-on: windows-latest

    permissions:
      checks: write
      contents: read

    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v4

      # Étape 2 : Build du projet
      - name: Build solution
        run: dotnet build

      # Étape 3 : Exécution des tests avec log .trx
      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

      # Étape 4 : Upload des résultats de test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/*.trx

      # Étape 5 : Publication des résultats dans GitHub UI
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: TestResults/*.trx
          reporter: dotnet-trx
